### ISSUE TITLE
[partitions]: Rename options and change images

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#10]
![partitions](https://cloud.githubusercontent.com/assets/840070/6652429/a5166056-ca6e-11e4-9903-fbbf6d4d46b9.jpg)
We can discuss some images that might fit the above ideas here.

**Comment by teo** [comment]
I agree it's time to fix up these actions.

I think the "Erase disk" item should say that the OS will be installed, because it's not just an erase operation, it's an "erase + automatic partitioning + automatic mount points + automatic bootloader" operation. But I agree that we could make it less verbose and avoid writing the full name "Generic Linux 1.0 LTS yadda yadda", and use the short name "Generic 1.0" in all situations in the partitioning module (the branding mechanism comes with a full array of product branding strings of varying length). So in this case the first line would be "Erase disk and install Generic 1.0".

The second entry can contain the "split partition" wording if you like, but I try to avoid being too technical here, and instead focus on the end result: the user wants his new OS alongside an old one, and we should try to avoid cluttering the discourse with implementation details. What we represent as a "split" operation is actually a "shrink+new partition" operation.
What do you think about the following text: "Install Generic 1.0 alongside Ubuntu 14.04 LTS", and below that "The installer will shrink the Ubuntu 14.04 volume to make room for Generic 1.0. You can choose which operating system you want each time the computer starts up." ?

For the third entry, I fear that "replace partition" might cause confusion. The operation is more explicit if we declare that we erase the contents and install Generic 1.0 there. Right now the feature allows the user to choose a partition (but only if it's big enough), and this partition is formatted and used as system partition, regardless if it's initially a system or a data partition, so it's not just "replace OS with the target OS", it's "replace the contents of any chosen partition with the target OS". My concern is that "Replace a partition with Generic 1.0" would be less precise than than the text we already have, because we're not even replacing a partition, we're just overwriting its contents.
Maybe there's some other wording that expresses even better what we want to do? Just calling it "replace partition" might create more problems than it solves.

Finally, I agree with changing the wording of the fourth entry, but I believe that "Manual partitioning" would be more accurate than "Manual installation".

Maybe I'm too focused on correctness here. The way I see it we do need shorter, more readable text. I just wouldn't want to make our UI less clear in the process.

Once the wording is fixed I can work with the VDG to get some new icons to represent these actions.

**Comment by teo** [comment]
Current state in master, with fixed up text. Icons by Jens, screenshots by Anke (KaOS).
![snapshot72_1](https://cloud.githubusercontent.com/assets/126364/6984600/d7488eca-da2a-11e4-9921-7b6876f26ad8.png)
![snapshot73_1](https://cloud.githubusercontent.com/assets/126364/6984601/d74ef0d0-da2a-11e4-9abe-7a555a828fcc.png)

**Comment by teo** [comment]
Can this be closed?
