### ISSUE TITLE
[partition-page]: layout and text adjustments

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#18]
![cala2 0-edit](https://cloud.githubusercontent.com/assets/840070/11758344/b6a00b16-a01e-11e5-9eda-b4b87f97e60c.png)

change text:
- in front of storage dropdown: "Pick a storage device: "
- remove all text that is striked through red above
- change "Current state" to "Before"
- change "Your changes" to "After"

partitions:
- label all partitions with whats installed instead of /dev/sda1, etc.
- proposal to simplify: dont list sda3 as an extended umbrella partition, only list and color label the partitions inside

**Comment by teo** [comment]
This is the current state, this time booting in EFI mode on a system with existing BIOS/MBR partitioning.
I've updated all the strings as you proposed, and I've refactored the way os-prober reads existing OS information to make it available in the PartitionModel.
![3xgmfxq](https://cloud.githubusercontent.com/assets/126364/11818454/afea1fde-a35a-11e5-99ed-0350b0d59311.png)

As for labeling partitions, not all partitions are system partitions for some OS, so it's not always possible to label them. If you dislike "/dev/sda4", I can do something like "Data partition (sda4)". In this case, since there might be multiple non-OS partitions, it could be useful to at least keep the "sda4" part to uniquely identify a partition. Is this ok, or would you prefer some other wording?

**Comment by star-buck** [comment]
I would not show 1 MB partition in legend.
I would not show sda3 in Before bar nor legend either.
I would not label it "new root partition", but simply Netrunner Rolling
(system name) and not add any "New" in front of any labels in legend (root,
swap).

What are sda4 sda5 sda6 on system wise?

**Comment by star-buck** [comment]
I would also remove word "partition" in legend labels, so its simply
"swap", "EFI", etc. Also logarythmicly shwing some red pixels of the after
bar for EFI would be nice to see location of EFI.

**Comment by teo** [comment]
sda4, sda5 and sda6 are just data partitions (the screenshot is from is the test system which gets repartitioned all the time to test things, trigger corner cases, etc.). In a real world scenario they could be a home partition or a boot partition of another system, or an NTFS data partition created from Windows for storage, etc. In these cases these partitions cannot be associated with an existing OS.

Regarding the extended partition, while I agree it's best to keep things as simple as possible, I fear that an attempt at oversimplification might create more problems than it solves. I believe sda3 (the extended partition) to be such a case. It is unfortunate that the user even has to deal with an extended partition, but that's necessary because it is a workaround needed by the DOS partition table type, and the user has to understand that. The partition needs to be selectable in partitioning operations (because it is by all means a partition that can be managed), it has to be evident that certain operations are not possible across extended partition boundaries (e.g. moving, resizing), and that because of the existence of an extended partition, partitions cannot be created at all in some places. For instance, if you've reached the 4 primary partition limit, the only place you can create new partitions is inside the extended partition as logical partitions, and creation anywhere else would fail. If the extended partition was hidden from the view, the user could incur situations where an operation is not possible, but it's not clear nor foreseeable why. The DOS partition table is a bad system in this day and age, but insofar as we have to use it, I believe we should help educate the user, and assist the user in making informed decisions.

In other words, even if I hid the representation of the extended partition, I couldn't hide the limitations and consequences of its existence, and I believe that having a UI that tries to reflect these limitations while hiding where they come from would prove to be much more confusing and error-prone for the user than a UI which shows the extended partition as it is.

Having said that, I'm still in favor of streamlining the labels to make them take less space and be more informative. So for instance, instead of the label saying
```
/dev/sda3
210.2 GiB  extended
```
i can turn it to
```
Extended (sda3)
210.2 GiB
```
or
```
Extended
210.2 GiB
```
This should be informative enough, because the extended partition is only 1 per partition table anyway, so it doesn't necessarily need to be uniquely idenfied with a full device node path.

I am also renaming the "New..." wording, and I will investigate possible ways for making tiny partitions like the EFI one show up in the bars view.

**Comment by star-buck** [comment]
Update:
After testing the beta1, here is further refurbishment:
![partman-1](https://cloud.githubusercontent.com/assets/840070/11916063/5a1ab2f6-a6bd-11e5-9692-7057d4f9d8cb.png)
![partman-3](https://cloud.githubusercontent.com/assets/840070/11916062/5a193bec-a6bd-11e5-806d-74f048db0e2a.png)

Lets move the hr-line below the 4 possible options, that is below the Manual Partitioning option.
So then any more text or manual selection is done or blend in / updated below that line, e.g. the todo text from the Replace option.

Further I assume that the alongside second page will be also merged into the main partition page below that line, where the user can select the partition to shrink and drag the size.
