### ISSUE TITLE
[kde partitionmanager]: enable rename usb stick

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#22]
I know its not calamares, but for convinience, maybe you can find a way for new partition manager to allow renaming usb sticks, e.g.:
https://forum.kde.org/viewtopic.php?f=225&t=106855

**Comment by teo** [comment]
I've been researching this issue. The gist of it is that KDE Partition Manager *can* change what's intended as the USB stick's name, except in some special cases in which nothing I've tried can (not even GParted).

What's *usually* presented as the name of the USB stick is the label of the partition on it.
This works assuming the USB stick has an MSDOS partition table, with a single partition on it. If the USB storage device has more than one partition, all of them appear with their respective filesystem labels.
Both GParted and KDE Partition Manager support changing a filesystem's label.
In KDE Partition Manager, one has to right-click on the partition, then Properties, set a new label, OK and then Apply.
![fslabel](https://cloud.githubusercontent.com/assets/126364/11956537/48ca00ec-a8bb-11e5-82a3-c645e3477f9f.png)
So a filesystem label is the common way to set a USB stick's name, and this works.

If a filesystem is unlabeled however (for whatever reason), or if the device doesn't have a partition table, a string still gets picked up from *somewhere*, and I'm not sure where from yet. In some situations, where no strings are available at all, a UUID is used.
A hypothesis in one of my test cases is also that the string I got in the Plasma disks applet might even be left over from a previous filesystem created with no partition table.

Changing this string is not supported by GParted nor by KDE Partition Manager, in fact I haven't yet managed to find out what this fallback string *is*: all I know is that it's not tied to a newly created filesystem, partition or partition table.

However, considering that the Plasma disks applet shows this string, there must be a way to access it. I can pursue this further to get to the bottom of it, but now we know that it's not a trivial UI thing in KDE Partition Manager so it might take a while. Should I go on?

**Comment by star-buck** [comment]
Just leave investigation there for now, we need to get calamares partition
page done.

**Comment by teo** [comment]
I just had an idea now and did a really quick check with dd and Okteta, and my intuition proved to be correct: the only other potential string that pops up is an El Torito signature.

El Torito is the format used by ISO9660 bootable ISOs, including some bootable USB sticks, and it writes its information at offset 32768 on the disk. What happens, is that if you have a bootable USB stick with an El Torito signature (e.g. an Archlinux or Kubuntu ISO), and then you create a new partition table on it, with a new partition which seemingly overwrites everything, in reality not everything is overwritten. The MBR finishes at offset 512, a lot before the start of El Torito information, which doesn't get overwritten, because the first partition only starts later on.

There is nothing I can do here even if this was a priority: this string cannot be reliably changed, the only way to set it is by baking a whole new ISO and dumping it on the stick, and the only way to wipe it is to manually clear the start of the disk to /dev/zero *before* creating a partition table.

It is still not an issue if the partitions have a label, but now we know what's up. If anything, this is a Plasma disks applet issue, which should probably not pick up an El Torito signature if a partition table exists.

I'm back on Calamares partition page tasks now.
