### ISSUE TITLE
reported bootloader/gpt issue

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#33]
He is talking about Latest 17.01, so about calamares in last paragaph of this comment:
http://www.ocsmag.com/2016/12/05/best-kdeplasma-distro-of-2016/#comment-3085305844

**Comment by demmm** [comment]
Bug reports for this was opened last September:
https://calamares.io/bugs/browse/CAL-388, not just a GPT issue, is true for all automated options.  No susch issues for manual selection.

**Comment by kkofler** [comment]
Bug reports in Calamares go to https://calamares.io/bugs – you can log in there with your GitHub account.

**Comment by star-buck** [comment]
Definitely needs attention:
http://forums.netrunner.com/showthread.php?tid=24038

**Comment by demmm** [comment]
@star-buck 
Quite a few tests run with this commit:
https://github.com/calamares/calamares/commit/f3848cd42853e2ddc3781b24c091314f2a21fc76

So far issue is fixed here.

**Comment by adriaandegroot** [comment]
Closing this one since @demmm reports it fixed; there are newer bootloader problems reported since then, but those have been filed in appropriate downstream- or calamares-main-repo. (Also closing because I'd like to delete this repo -- it's just spreading Calamares issues and improvements over more places).
