### ISSUE TITLE
combine language + location + keyboard layout on one page

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#6]
idea from llectronics:

I think language + location + keyboard layout can be combined on one page. 
My idea is here that the user has its world map and clicks on a country / region. This automatically sets the correct timezone but also offers in a overlay popup the default language and keyboard layout of that region. (dropdown menus) 
Accepting with OK will then go to the next page. 
The reason to do this is because to many pages frustrate users. 
![calamares-language-location-mockup](https://cloud.githubusercontent.com/assets/3415572/3199226/4d758764-ed65-11e3-95d4-627bde41e190.png)

**Comment by teo** [comment]
I agree that many pages with questions and more questions frustrate users, and I want to address that, but there are some important issues with the proposal above.

0) Language should be the very first thing that's asked, because it's used for localization of the whole application before anything else. Sure, further keyboard/location settings can then be autodetected based on the chosen language, but language should come first and separately. Ubuntu and Windows installers do this too, for the same reasons, and both have some well-done guessing. I believe this is the direction we should move towards.
1) The above mockup breaks the top-down left-right workflow. This is very bad: an Ok button in a variable position within a wizard page that would normally have "Next" as an accept action. Also, it wouldn't look as good if popping up for a user in Alaska or New Zealand because of proximity to the edge on an unscrollable map.
2) It does away with the keyboard preview, which is potentially very useful when there are multiple variants of a keyboard layout for the same language. I do concede that the current UI is far from perfect, and that keyboard layouts should be grouped better (http://calamares.io/bugs/browse/CAL-4).
3) Post-1.0 plans include replacing the world map with a map based on Marble. This is badly needed because the current map is not scalable, and the change is already accounted for in the VDG's UX designs (see bottom of page https://community.kde.org/KDE_Visual_Design_Group/Calamares_Design_Project), so any code I write now would go against that design and would have to be redone when we get a proper world map.

I'd definitely like to, and plan to, improve location+keyboard, but I don't believe the proposal above would be a significant UX improvement, aside from the fact that there would be 1 page instead of 2.

**Comment by Salamandar** [comment]
I'm trying to install Fedora with their Anaconda installer and they got something right : the current keyboard configuration is *always* on-screen.
(That's basically the only thing they got right ;) )

**Comment by adriaandegroot** [comment]
Closing this one as "fallen by the wayside". This illustrates that having multiple issue trackers and places for feature-requests is problematic; if anything, this issue belongs in the main Calamares tracker as an enhancement. Though, for all the reasons Teo mentioned two years ago, I don't think it's a good idea to change the workflow like this.

Currently, timezone and language and locale info live on one page, and keyboard layout is on another. We could talk about merging them into one page -- there is space for a *Keyboard layout* line and button, although that again hits the whole "breaking workflow" problem that the existing *change* buttons already have.
